spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?characterEcoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: mysql123
    druid:
      max-active: 10
      min-idle: 2
      filters: inject
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.geektime: debug